function New-Case {
  param(
    [string]$Id,
    [string]$Title,
    [string]$Area,
    [string]$Type,
    [string]$Priority,
    [string[]]$Preconditions,
    [string[]]$Steps,
    [string[]]$Expected,
    [hashtable]$References
  )
  [ordered]@{
    id = $Id
    title = $Title
    area = $Area
    type = $Type
    priority = $Priority
    preconditions = $Preconditions
    steps = $Steps
    expected_results = $Expected
    references = $References
  }
}

$cases = @(
  (New-Case 'DEPT-001' 'Department Management page loads with all primary controls' 'listing_search_and_filters' 'smoke' 'critical' @('User is authenticated with access to Department Management.') @('Navigate to /admin/departments.','Observe the search field, Search button, Division filter, Status filter, Columns selector, table, rows-per-page control, pagination controls, Add New button, and Download Excel button.') @('Department Management page loads without client or server errors.','Primary listing and action controls are visible and enabled according to permission.','The listing area renders rows or a valid empty state.') @{pages=@('/admin/departments');elements=@('Department search','Search','Division filter','Status filter','Columns selector','Department listing','Rows per page','Next page','Previous page','Add New')}),
  (New-Case 'DEPT-002' 'Search returns matching records for a valid department name' 'listing_search_and_filters' 'functional' 'critical' @('At least one known department exists.') @('Open /admin/departments.','Enter a valid existing department name in the Department search field.','Click Search.') @('Search results are shown.','Returned rows match the searched department according to supported search behavior.','Clearly unrelated rows are not shown.') @{flows=@('search_departments');capabilities=@('Search departments by name and show a no-results state for unmatched input.')}),
  (New-Case 'DEPT-003' 'Search shows the no-results state for an unmatched department name' 'listing_search_and_filters' 'negative' 'high' @('User is on /admin/departments.') @('Enter a department name that does not exist.','Click Search.') @('A visible no-results state is displayed.','The page indicates that no departments were found.','The user can perform another search without reloading the page.') @{validations=@("An unmatched search returns a visible 'No departments found' state.")}),
  (New-Case 'DEPT-004' 'Search input handles leading and trailing spaces consistently' 'listing_search_and_filters' 'validation' 'medium' @('At least one known department exists.') @('Enter a valid department name with leading and trailing spaces.','Click Search.') @('Search behavior is consistent with normalized input.','The department is found if the underlying value matches after whitespace normalization.') @{elements=@('Department search','Search')}),
  (New-Case 'DEPT-005' 'Running a second search refreshes results instead of leaving stale rows' 'listing_search_and_filters' 'functional' 'medium' @('At least two searchable departments with different names exist.') @('Search for Department A.','Review the results.','Replace the search term with Department B and click Search again.') @('The result set refreshes for the second search.','Rows from the first search that do not match the second search are removed.') @{flows=@('search_departments')}),
  (New-Case 'DEPT-006' 'Division filter narrows the listing to the selected division' 'listing_search_and_filters' 'functional' 'high' @('Department data exists across more than one division.') @('Open /admin/departments.','Select a division from the Division filter.') @('The listing refreshes to show only departments for the selected division.','Rows outside the selected division are excluded.') @{flows=@('filter_by_division');cross_module_dependencies=@('Division data is required by both the page-level filter and the add/edit department form.')}),
  (New-Case 'DEPT-007' 'Resetting the Division filter restores the broader result set' 'listing_search_and_filters' 'functional' 'medium' @('A division filter value has been applied.') @('Apply a specific division filter.','Reset the Division filter to its default or all value.') @('The listing returns to the unfiltered or less-filtered state.','Departments from multiple divisions are visible again when allowed by other active filters.') @{elements=@('Division filter')}),
  (New-Case 'DEPT-008' 'Status filter narrows the listing to Active departments' 'listing_search_and_filters' 'functional' 'high' @('Active departments exist.') @('Open /admin/departments.','Select Active from the Status filter.') @('The listing refreshes to show only Active departments.','Inactive departments are excluded from the result set.') @{flows=@('filter_by_status')}),
  (New-Case 'DEPT-009' 'Status filter narrows the listing to Inactive departments' 'listing_search_and_filters' 'functional' 'high' @('Inactive departments exist.') @('Open /admin/departments.','Select Inactive from the Status filter.') @('The listing refreshes to show only Inactive departments.','Active departments are excluded from the result set.') @{flows=@('filter_by_status')}),
  (New-Case 'DEPT-010' 'Resetting the Status filter restores the broader result set' 'listing_search_and_filters' 'functional' 'medium' @('A status filter value has been applied.') @('Apply Active or Inactive status.','Reset the Status filter to its default or all value.') @('The listing returns to the unfiltered or less-filtered state for status.','Rows are recalculated correctly when other filters remain active.') @{elements=@('Status filter')}),
  (New-Case 'DEPT-011' 'Division and Status filters work correctly together' 'listing_search_and_filters' 'functional' 'high' @('Department data exists for multiple divisions and statuses.') @('Select a division.','Select a status.','Review the filtered rows.') @('Displayed rows satisfy both filters simultaneously.','Changing either filter recalculates the result set without stale rows.') @{flows=@('filter_by_division','filter_by_status')}),
  (New-Case 'DEPT-012' 'A filter combination with no matches shows a recoverable empty state' 'listing_search_and_filters' 'negative' 'high' @('There is at least one filter combination that returns no departments.') @('Apply a division and status combination that has no matching rows.','Observe the listing state.','Reset one filter.') @('The listing shows a valid empty state rather than stale data.','After resetting one filter, the listing recovers and shows recalculated results.') @{flows=@('filter_by_division','filter_by_status')}),
  (New-Case 'DEPT-013' 'Search, division filter, and status filter remain internally consistent together' 'listing_search_and_filters' 'functional' 'high' @('Test data supports search, division filtering, and status filtering.') @('Search for a valid department keyword.','Apply a division filter.','Apply a status filter.','Review the resulting rows.') @('Displayed rows satisfy the active search and both filters.','No stale rows from previous states remain visible.') @{flows=@('search_departments','filter_by_division','filter_by_status')}),
  (New-Case 'DEPT-014' 'Department column sort toggles the record order' 'grid_sort_pagination_export' 'functional' 'high' @('At least three departments exist with distinct names.') @('Click the Department column header once.','Observe the row order.','Click the Department column header again.') @('The Department column sort is applied.','The displayed order changes between supported sort states.','Displayed data stays consistent with the active result set.') @{flows=@('sort_department_column');capabilities=@('View department data in a tabular grid with sortable columns.')}),
  (New-Case 'DEPT-015' 'Created On column sort toggles chronological order' 'grid_sort_pagination_export' 'functional' 'high' @('Multiple departments exist with different creation timestamps.') @('Click the Created On column header once.','Observe the row order.','Click the Created On column header again.') @('The listing is reordered by creation date.','The sort direction changes across repeated clicks or supported sort states.') @{flows=@('sort_created_on_column')}),
  (New-Case 'DEPT-016' 'Sorting operates only within the active filtered dataset' 'grid_sort_pagination_export' 'functional' 'high' @('A search term or filter has already narrowed the result set.') @('Apply a search or filter.','Sort by Department or Created On.','Review the rows.') @('Sorting changes the order of the current result set only.','Rows that do not match active search or filters are not reintroduced.') @{flows=@('search_departments','filter_by_division','sort_department_column','sort_created_on_column')}) )
)
$cases += @(
  (New-Case 'DEPT-017' 'Columns selector can hide and show listing columns' 'grid_sort_pagination_export' 'functional' 'medium' @('Columns selector is available on the page.') @('Open the Columns selector.','Hide one non-critical column.','Verify the table updates.','Re-enable the same column.') @('Selected column visibility changes are reflected in the table.','Re-enabled columns become visible again without breaking layout.') @{flows=@('open_columns_selector');capabilities=@('Adjust visible columns from the columns selector.')}),
  (New-Case 'DEPT-018' 'Grid functions continue to work after columns are changed' 'grid_sort_pagination_export' 'functional' 'medium' @('At least one optional column can be hidden using the Columns selector.') @('Hide one non-critical column.','Perform a sort or paginate to another page.','Review the table.') @('The table remains usable after column visibility changes.','Sort or pagination continues to work without layout corruption or missing essential controls.') @{flows=@('open_columns_selector','paginate_next')}),
  (New-Case 'DEPT-019' 'Rows per page control updates the page size' 'grid_sort_pagination_export' 'functional' 'high' @('There are more records than the default page size.') @('Open the rows-per-page control.','Change the page size from the default value to 10.') @('The listing refreshes using the selected page size.','The number of visible rows matches the selected page size or remaining record count on the last page.','Pagination count recalculates correctly.') @{flows=@('change_rows_per_page_10');capabilities=@('Change rows per page and paginate through the department listing.')}),
  (New-Case 'DEPT-020' 'Next and Previous pagination navigate correctly between pages' 'grid_sort_pagination_export' 'functional' 'high' @('There are enough records to create at least two pages.') @('Go to page 1 of the listing.','Click Next.','Verify the second page data.','Click Previous.') @('Next navigates to the next page of rows.','Previous returns to the prior page.','Page content changes consistently with pagination state.') @{flows=@('paginate_next','paginate_previous')}),
  (New-Case 'DEPT-021' 'Pagination boundary states disable Previous on first page and Next on last page' 'grid_sort_pagination_export' 'validation' 'high' @('There are enough records to create more than one page.') @('Open the first page of the listing.','Observe the Previous button state.','Navigate to the last page.','Observe the Next button state.') @('Previous is disabled or unavailable on the first page.','Next is disabled or unavailable on the last page.') @{validations=@('Pagination boundaries are enforced with Previous disabled on the first page and Next disabled on the last page.')}),
  (New-Case 'DEPT-022' 'Pagination recalculates correctly after the result set is narrowed' 'grid_sort_pagination_export' 'functional' 'high' @('The unfiltered listing spans multiple pages.') @('Verify the listing has multiple pages.','Apply a search or filter that substantially narrows the result set.','Review the pagination controls and counts.') @('Pagination reflects the reduced result set.','The user is not left on an invalid page number after the result set changes.') @{flows=@('search_departments','filter_by_division','filter_by_status')}),
  (New-Case 'DEPT-023' 'Download Excel exports the current department dataset' 'grid_sort_pagination_export' 'functional' 'medium' @('Download Excel is visible for the current user.','Browser download handling is enabled in the test environment.') @('Open /admin/departments.','Optionally apply a search or filter.','Click Download Excel.','Open the downloaded file.') @('A file download is triggered successfully.','The export contains department listing data.','If search or filters were active, the exported data matches the intended dataset according to product behavior.') @{coverage_gap_origin=@('Download Excel was visible but intentionally not invoked.')}),
  (New-Case 'DEPT-024' 'Add Department modal opens with all expected controls' 'add_department' 'smoke' 'critical' @('User has permission to create departments.') @('Click Add New on /admin/departments.') @('Add Department modal opens successfully.','Department Name, Description, Division, Locations, Status, and Cancel controls are visible.','The form is ready for data entry.') @{flows=@('open_add_department');pages=@('/admin/departments#add-department');elements=@('Add Department modal','Department form name','Department form description','Department form division','Department form locations','Department form status','Cancel add department')}),
  (New-Case 'DEPT-025' 'Cancel in Add Department closes the modal without saving' 'add_department' 'functional' 'high' @('Add Department modal is open.') @('Enter data into one or more fields.','Click Cancel.') @('The Add Department modal closes.','No new department is created.','The listing remains unchanged.') @{flows=@('select_division_location_status_then_cancel')}),
  (New-Case 'DEPT-026' 'Reopening Add Department does not retain canceled unsaved data' 'add_department' 'functional' 'medium' @('User can open and cancel the Add Department modal.') @('Open Add Department.','Enter temporary values and click Cancel.','Open Add Department again.') @('The modal opens in a clean state.','Canceled unsaved values are not retained unless draft persistence is an intended product feature.') @{flows=@('open_add_department','select_division_location_status_then_cancel')}),
  (New-Case 'DEPT-027' 'Submitting Add Department with all mandatory fields empty shows validation errors' 'add_department' 'validation' 'critical' @('Add Department modal is open in an environment where form submission is allowed.') @('Leave all fields empty.','Attempt to submit the form.') @('Submission is blocked.','Required validation is shown for Department Name, Division, and Locations.','No department record is created.') @{validations=@('Department Name is marked required in the add flow.','Division is marked required in the add flow.','Locations is marked required in the add flow.');coverage_gap_origin=@('Validation error messages for missing required fields were not triggered because forms were not submitted.')}),
  (New-Case 'DEPT-028' 'Department Name is mandatory in Add Department' 'add_department' 'validation' 'high' @('Add Department modal is open.') @('Populate Division and Locations with valid values.','Leave Department Name empty.','Attempt to submit.') @('Submission is blocked.','Validation indicates Department Name is required.','Other entered values remain available for correction unless the product intentionally resets them.') @{validations=@('Department Name is marked required in the add flow.')}),
  (New-Case 'DEPT-029' 'Division is mandatory in Add Department' 'add_department' 'validation' 'high' @('Add Department modal is open.') @('Enter a valid Department Name.','Leave Division unset.','Attempt to submit.') @('Submission is blocked.','Validation indicates Division is required.') @{validations=@('Division is marked required in the add flow.')}),
  (New-Case 'DEPT-030' 'Locations are mandatory in Add Department' 'add_department' 'validation' 'high' @('Add Department modal is open.') @('Enter a valid Department Name.','Select a valid Division.','Leave Locations empty.','Attempt to submit.') @('Submission is blocked.','Validation indicates Locations are required.') @{validations=@('Locations is marked required in the add flow.')}),
  (New-Case 'DEPT-031' 'Status defaults to Active in a fresh Add Department form' 'add_department' 'validation' 'high' @('Add Department modal is opened fresh.') @('Observe the Status field before making any manual selection.') @('Status defaults to Active.') @{validations=@('Status defaults to Active and supports switching to Inactive.')}) )
)
$cases += @(
  (New-Case 'DEPT-032' 'Add Department allows changing status from Active to Inactive' 'add_department' 'functional' 'medium' @('Add Department modal is open.') @('Open the Status control.','Change the value from Active to Inactive.') @('Status selection updates to Inactive.','The form remains usable for submission after the change.') @{validations=@('Status defaults to Active and supports switching to Inactive.')}),
  (New-Case 'DEPT-033' 'Locations list is constrained by the selected Division in Add Department' 'add_department' 'functional' 'critical' @('Multiple divisions exist with different location sets.') @('Open Add Department.','Select Division A and review the available Locations.','Change to Division B and review the available Locations again.') @('Location options are populated based on the selected division.','Location options change when the division changes.','Locations outside the selected division are not offered.') @{capabilities=@('Resolve location options based on the selected division in the department form.');validations=@('Location choices are dependent on the selected division before save, indicating a cross-field dependency.')}),
  (New-Case 'DEPT-034' 'Changing Division refreshes or clears incompatible Locations in Add Department' 'add_department' 'validation' 'high' @('At least two divisions exist with different location sets.') @('Open Add Department.','Select Division A and choose one or more Locations.','Change the Division to Division B.') @('Locations are refreshed for the newly selected division.','Any locations that are no longer valid are cleared or explicitly flagged before submission.') @{cross_module_dependencies=@('Location options depend on the selected division, indicating a dependency on location master data.')}),
  (New-Case 'DEPT-035' 'Creating a department with valid mandatory data succeeds' 'add_department' 'functional' 'critical' @('User has create permission.','Safe unique test data is available.','Form submission is permitted in the target environment.') @('Open Add Department.','Enter a unique Department Name.','Optionally enter Description.','Select a valid Division.','Select one or more valid Locations.','Keep Status as Active.','Submit the form.') @('The department is created successfully.','The modal closes or success feedback is shown.','The new department appears in the listing.') @{coverage_gap_origin=@('Add Department submit was intentionally not executed.')}),
  (New-Case 'DEPT-036' 'Creating a department with Inactive status succeeds' 'add_department' 'functional' 'high' @('User has create permission.','Safe unique test data is available.','Form submission is permitted in the target environment.') @('Open Add Department.','Enter valid mandatory data.','Set Status to Inactive.','Submit the form.') @('The department is created successfully.','The created record is stored with Inactive status.') @{elements=@('Department form status')}),
  (New-Case 'DEPT-037' 'A newly created department is searchable and visible in the correct status filter' 'add_department' 'data_integrity' 'high' @('A new department was created during the test run.') @('Search for the newly created department.','Verify the record appears.','Apply the status filter matching the created record and verify the record is present.','If applicable, apply the opposite status filter and verify the record is absent.') @('The newly created record is retrievable by search.','The record appears under the correct status view.','The record does not appear under the wrong status-only view.') @{flows=@('search_departments','filter_by_status')}),
  (New-Case 'DEPT-038' 'Edit Department modal opens with existing values prefilled' 'edit_department' 'smoke' 'critical' @('At least one editable department record exists.','User has edit permission.') @('Click Edit department for an existing row.') @('Edit Department modal opens successfully.','Existing Department Name and Description are prefilled.','Current Division, Locations, and Status are shown for the selected record.') @{flows=@('open_edit_department');capabilities=@('Open the Edit Department modal and inspect prefilled department values.')}),
  (New-Case 'DEPT-039' 'Cancel in Edit Department closes the modal without updating the record' 'edit_department' 'functional' 'high' @('Edit Department modal is open for an existing record.') @('Change one or more editable values.','Click Cancel.','Reopen the same record.') @('The Edit Department modal closes.','No changes are saved to the department record.','Original values are still shown when the record is reopened.') @{flows=@('cancel_edit_department')}),
  (New-Case 'DEPT-040' 'Editing Department Name and Description updates the record successfully' 'edit_department' 'functional' 'critical' @('User has edit permission.','At least one editable department exists.','Form submission is permitted in the target environment.') @('Open Edit Department for an existing record.','Modify Department Name and Description.','Submit the update.') @('The update succeeds.','Reopening the record shows the new values.','Updated values appear in the listing and search results.') @{coverage_gap_origin=@('Update Department submit was intentionally not executed.')}),
  (New-Case 'DEPT-041' 'Editing department status updates the listing correctly' 'edit_department' 'functional' 'high' @('User has edit permission.','At least one editable department exists.','Form submission is permitted in the target environment.') @('Open Edit Department for an existing record.','Change the Status value.','Submit the update.','Filter the listing by the updated status.') @('The update succeeds.','The record appears under the new status filter after save.') @{elements=@('Department form status','Status filter')}),
  (New-Case 'DEPT-042' 'Changing Division during edit refreshes the available Locations' 'edit_department' 'functional' 'high' @('Editable department exists.','At least two divisions exist with different location sets.') @('Open Edit Department.','Change the Division to a different value.','Inspect the Locations control.') @('Location choices refresh according to the newly selected division.','No locations outside the chosen division are offered.') @{cross_module_dependencies=@('Location options depend on the selected division, indicating a dependency on location master data.')}),
  (New-Case 'DEPT-043' 'Edit submission is blocked when required fields become invalid' 'edit_department' 'validation' 'high' @('User has edit permission.','An editable department exists.','Form submission is permitted in the target environment.') @('Open Edit Department.','Clear a required field such as Department Name or make Locations invalid after changing Division.','Attempt to submit.') @('Submission is blocked.','Required-field validation is shown for the invalid field or dependency state.','No unintended update is committed.') @{validations=@('Create and update submit buttons were intentionally not invoked, so server-side validation messaging was not exercised.')}),
  (New-Case 'DEPT-044' 'Department Management access is restricted for users without the required permission' 'security_access' 'security' 'high' @('A non-authorized user account is available.') @('Sign in with a user who lacks Departments admin access.','Attempt to navigate to /admin/departments.') @('Access is denied, redirected, or the page and action controls are hidden according to the security design.','Unauthorized users cannot create or edit departments.') @{cross_module_dependencies=@('Access to Department Management and edit actions depends on authenticated admin/security context.')}) )
)

function Get-Counts {
  param([object[]]$Items,[string[]]$Order)
  $result = [ordered]@{}
  foreach ($name in $Order) {
    $count = @($Items | Where-Object { $_ -eq $name }).Count
    if ($count -gt 0) { $result[$name] = $count }
  }
  $result
}

$priorityCounts = Get-Counts ($cases | ForEach-Object { $_.priority }) @('critical','high','medium')
$typeCounts = Get-Counts ($cases | ForEach-Object { $_.type }) @('smoke','functional','validation','negative','security','data_integrity')
$areaCounts = Get-Counts ($cases | ForEach-Object { $_.area }) @('listing_search_and_filters','grid_sort_pagination_export','add_department','edit_department','security_access')

$doc = [ordered]@{
  module = 'Departments'
  generated_from = 'ai_knowledge/modules/Departments/app_intelligence.json'
  generated_on = '2026-04-07'
  generation_basis = [ordered]@{
    pages_covered = 6
    elements_covered = 22
    documented_capabilities = 8
    documented_validations = 8
    documented_flows = 13
    coverage_gaps_considered = 5
    target_style = 'comprehensive_structured_practical_coverage'
  }
  assumptions_and_execution_notes = @(
    'Create and update submission cases should run only in a non-production-safe environment with disposable test data.',
    'At least two divisions, multiple locations, Active and Inactive departments, and more than one listing page should exist to execute the full suite without setup blockers.',
    'Exact validation text, export file naming, and server-side uniqueness or length rules were not explicitly documented in the source intelligence and should be asserted against product requirements where applicable.',
    'Download Excel was visible in exploration artifacts but was not executed during module crawling, so export coverage is included as a recommended execution area.'
  )
  scope = [ordered]@{
    primary_page = '/admin/departments'
    in_scope_areas = @('Department listing','Search','Division filter','Status filter','Combined query states','Columns selector','Sorting','Pagination','Download Excel','Add Department modal','Edit Department modal','Cross-field dependency between Division and Locations','Validation behavior','Permission and access checks')
    out_of_scope_notes = @('Exact backend validation wording is not guaranteed by the source intelligence.','Department name uniqueness, max length, and special-character business rules are not explicitly documented in the source intelligence.','Global admin navigation outside the Departments module remains out of scope because the source crawl ran in module mode.')
  }
  test_case_summary = [ordered]@{
    total = $cases.Count
    by_priority = $priorityCounts
    by_type = $typeCounts
    by_area = $areaCounts
  }
  test_cases = $cases
}

$doc | ConvertTo-Json -Depth 8 | Set-Content -Path 'ai_knowledge/testcases_Departments.json'

